php_settings:
  version: 7.4
whitelist:
  mysite:
    security:
      - "13.54.196.117"
    admin:
      - "13.54.196.117"
  cbss4:
    security:
      - "13.54.196.117"
    admin:
      - "13.54.196.117"
