php_settings:
  version: 7.4
whitelist:
  mysite:
    admin:
      "3.3.3.3": "foo bar"
      "4.4.4.4": "bar foo"
      "13.54.196.117": "silverstripe office vpn"
    security:
      5.5.5.5: "foofoo"
      "6.6.6.6": "barbar"
      "13.54.196.117": "silverstripe office vpn"
